<style type="text/css">
	.text{width: 100%;}
	.text_field_name{font-weight: bold;}
	#field_remove{font-weight: bold; margin: 0 5px; padding: 0 3px; color: #aaa; cursor: pointer; border: 1px solid gray; background-color: #eee;}
	#field_remove:hover{color: red; background-color: #bbb;}
</style>
<h4>Step 3: Details of product</h4>
<table class="table" id="table_step3">
	<tr>
		<td><label for="display">Display:</label></td>
		<td><input type="text" class="text" name="display" id="display"></td>
	</tr>
	<tr>
		<td><label for="os">OS:</label></td>
		<td><input type="text" class="text" name="os" id="os"></td>
	</tr>
	<tr>
		<td><label for="cpu">CPU:</label></td>
		<td><input type="text" class="text" name="cpu" id="cpu"></td>
	</tr>
	<tr>
		<td><label for="camera">Camera:</label></td>
		<td><input type="text" class="text" name="camera" id="camera"></td>
	</tr>
	<tr>
		<td><label for="internal_memory">Internal memory:</label></td>
		<td><input type="text" class="text" name="internal_memory" id="internal_memory"></td>
	</tr>
	<tr>
		<td><label for="ram">RAM:</label></td>
		<td><input type="text" class="text" name="ram" id="ram"></td>
	</tr>
	<tr>
		<td><label for="battery">Battery:</label></td>
		<td><input type="text" class="text" name="battery" id="battery"></td>
	</tr>
</table>
<table class="table">
	<tr>
		<td colspan="2">
			<input type="button" id="add_field" value="Add field">
		</td>
	</tr>
	<tr>
		<td><input type="button" value="Previous step 2" onClick="prevStep2();"></td>
		<td><input type="button" value="Create" onClick="createPro();"></td>
	</tr>
</table>
<script type="text/javascript">
	$('#add_field').click(function(){
		if(total_fields==0){
			$('#table_step3').append('<tr><td><span id="field_remove" data-id="'+total_fields+'" title="remove">&Chi;</span><input type="text" class="text_field_name" id="name'+total_fields+'" name="field_name'+total_fields+'" placeholder="typing field name...">: </td><td><input type="text" class="text" id="field'+total_fields+'" name="field_content'+total_fields+'" placeholder="typing content..."></td></tr>');
			total_fields++;
		}
		else if(total_fields>0){
			if($("input[name='field_name"+(total_fields-1)+"']").val()=='' && $("input[name='field_name"+(total_fields-1)+"']").parent().parent().css('display')!='none')
				$("input[name='field_name"+(total_fields-1)+"']").focus();
			else if($("input[name='field_content"+(total_fields-1)+"']").val()=='' && $("input[name='field_content"+(total_fields-1)+"']").parent().parent().css('display')!='none')
				$("input[name='field_content"+(total_fields-1)+"']").focus();
			else{
				$('#table_step3').append('<tr><td><span id="field_remove" data-id="'+total_fields+'" title="remove">&Chi;</span><input type="text" class="text_field_name" id="name'+total_fields+'" name="field_name'+total_fields+'" placeholder="typing field name...">: </td><td><input type="text" class="text" id="field'+total_fields+'" name="field_content'+total_fields+'" placeholder="typing content..."></td></tr>');
				total_fields++;
			}
		}
	});
	$(document).on('click', '#field_remove', function(){
		var id=$(this).data('id');
		$("input[name='field_name"+id+"']").val('');
		$(this).parent().parent().fadeOut(150);
	});
</script>