<h4>Step 2: Choose image</h4>
<form action="" method="post">
	<table class="table">
		<tr>
			<td><label>Image:</label></td>
			<td><input type="file" name="image" accept="image/*"></td>
		</tr>
		<tr>
			<td><input type="button" value="Previous step 1" onclick="loadStep1()"></td>
			<td><input type="button" value="Next step" onclick="loadStep3()"></td>
		</tr>
	</table>
</form>
<script type="text/javascript">
	function loadStep1()
	{
		$.ajax({
		   url: '/ajax/createproductstep1<?php if(isset($id)) echo '/id='.$id ?>',
		   type : "post",
		   dataType:"text",
		   success: function(data) {
		      $('#ajax').html(data);
		   },
		   error: function() {
		      $('#ajax').html('<p>An error has occurred</p>');
		   },
		});
	}

	function loadStep3()
	{
		$.ajax({
		   url: '/ajax/createproductstep3<?php if(isset($id)) echo '/id='.$id ?>',
		   type : "post",
		   dataType:"text",
		   success: function(data) {
		      $('#ajax').html(data);
		   },
		   error: function() {
		      $('#ajax').html('<p>An error has occurred</p>');
		   },
		});
	}
</script>