<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <script src="//code.jquery.com/jquery-2.1.4.js"></script>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->

    <?php echo $this->headLink(); ?>

    <!-- Scripts -->
    <?php echo $this->headScript(); ?>

</head>
<body>

    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Login</h4>
                </div>
                <div class="modal-body">
                    <form class="form">
                        <div class="form-group">
                            <label for="user">Username:</label>
                            <input type="text" class="form-control" name="user" id="user">
                        </div>
                        <div class="form-group">
                            <label for="pass">Password:</label>
                            <input type="password" class="form-control" name="pass" id="pass">
                        </div>
                        <div class="alert alert-danger fade in" id="error"></div>
                        <button type="button" class="btn btn-success" id="button">Login</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

    <div class="container">
        <?php echo $this->content; ?>
    </div>
    <?php echo $this->inlineScript() ?>
</body>
</html>
