<h3>Mobishop-Admin</h3>
</br>
Menu:
</br>
<ul>
	<li>User: <a href="<?php echo $this->url('user', array('action'=>'index')); ?>">go to page</a></li>
	<li>Shop information: <a href="<?php echo $this->url('shopinfo', array('action'=>'index')); ?>">go to page</a></li>
	<li>Advertise: <a href="<?php echo $this->url('advertise', array('action'=>'index')); ?>">go to page</a></li>
	<li>Manufacture: <a href="<?php echo $this->url('manufacture', array('action'=>'index')); ?>">go to page</a></li>
	<li>Product: <a href="<?php echo $this->url('product', array('action'=>'index')); ?>">go to page</a></li>
</ul>