<?php
$this->inlineScript()->appendFile('/js/create.js', 'text/javascript');
$this->headLink()->appendStylesheet('/css/style.css');
?>
<h3>Create Product</h3>
<div>
	<a href="<?php echo $this->url('product') ?>">List of products</a>
</div>
<div id="step1" class="step1">
	<h4>Step 1: Information</h4>
	<table class="table">
		<tr>
			<td><label for="name">Name:</label></td>
			<td><input type="text" name="name" id="name" required="required"></td>
		</tr>
		<tr>
			<td><label for="price">Price:</label></td>
			<td><input type="text" name="price" id="price" required="required"></td>
		</tr>
		<tr>
			<td><label>Manufacture:</label></td>
			<td>
				<select name="manufacture" id="manufacture">
				<?php foreach($manufactures as $manufacture): ?>
					<option value="<?php echo $manufacture->id ?>"><?php echo $manufacture->name ?></option>
				<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>
			<td><label for="inventory_number">Inventory number:</label></td>
			<td><input type="text" name="inventory_number" id="inventory_number" required="required"></td>
		</tr>
		<tr>
			<td><label for="date">Date:</label></td>
			<td><input type="text" name="date" id="date" required="required"></td>
		</tr>
		<tr>
			<td><label>Show:</label></td>
			<td>
				<select name="show" id="show">
					<option value="1">show</option>
					<option value="0">hiden</option>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2"><input type="button" value="Next step" onClick="showStep2();"></td>
		</tr>
	</table>
</div>
<div id="step2" class="step2">
	<h4>Step 2: Choose image</h4>
	<table class="table">
		<tr>
			<td><label>Image:</label></td>
			<td>
				<div id="thumbs">
					
				</div>
				<div id="files" data-current="1">
					<input type="file" id="image1" data-id="1" name="img_upload[]" accept="image/*" style="display: inline;">
				</div>
			</td>
		</tr>
		<tr>
			<td><input type="button" value="Previous step 1" onClick="showStep1();"></td>
			<td><input type="button" value="Next step" onClick="showStep3();"></td>
		</tr>
	</table>
</div>
<div id="step3" class="step3">
	<h4>Step 3: Details of product</h4>
	<table class="table" id="table_step3">
		<tr>
			<td><label for="display">Display:</label></td>
			<td><input type="text" class="text" name="display" id="display"></td>
		</tr>
		<tr>
			<td><label for="os">OS:</label></td>
			<td><input type="text" class="text" name="os" id="os"></td>
		</tr>
		<tr>
			<td><label for="cpu">CPU:</label></td>
			<td><input type="text" class="text" name="cpu" id="cpu"></td>
		</tr>
		<tr>
			<td><label for="camera">Camera:</label></td>
			<td><input type="text" class="text" name="camera" id="camera"></td>
		</tr>
		<tr>
			<td><label for="internal_memory">Internal memory:</label></td>
			<td><input type="text" class="text" name="internal_memory" id="internal_memory"></td>
		</tr>
		<tr>
			<td><label for="ram">RAM:</label></td>
			<td><input type="text" class="text" name="ram" id="ram"></td>
		</tr>
		<tr>
			<td><label for="battery">Battery:</label></td>
			<td><input type="text" class="text" name="battery" id="battery"></td>
		</tr>
	</table>
	<table class="table">
		<tr>
			<td colspan="2">
				<input type="button" id="add_field" value="Add field">
			</td>
		</tr>
		<tr>
			<td><input type="button" value="Previous step 2" onClick="showStep2();"></td>
			<td><input type="button" id="btn-create" value="Create"></td>
		</tr>
	</table>
</div>