<?php
$this->inlineScript()->appendFile('/js/create.js', 'text/javascript');
?>
<h3>Create Product</h3>
<div>
	<a href="<?php echo $this->url('product') ?>">List of products</a>
</div>
<div id="step1" class="step1">
	<h4>Step 1: Information</h4>
	<table class="table">
		<tr>
			<td><label for="name">Name:</label></td>
			<td><input type="text" name="name" id="name" required="required"></td>
		</tr>
		<tr>
			<td><label for="price">Price:</label></td>
			<td><input type="text" name="price" id="price" required="required"></td>
		</tr>
		<tr>
			<td><label>Manufacture:</label></td>
			<td>
				<select name="manufacture" id="manufacture">
						<option value="1">Asus</option>
						<option value="2">Apple</option>
				</select>
			</td>
		</tr>
		<tr>
			<td><label for="inventory_number">Inventory number:</label></td>
			<td><input type="text" name="inventory_number" id="inventory_number" required="required"></td>
		</tr>
		<tr>
			<td><label for="date">Date:</label></td>
			<td><input type="text" name="date" id="date" required="required"></td>
		</tr>
		<tr>
			<td><label>Show:</label></td>
			<td>
				<select name="show" id="show">
					<option value="1">show</option>
					<option value="0">hiden</option>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2"><input type="button" value="Next step" onClick="showStep2();"></td>
		</tr>
	</table>
</div>
<div id="step2" class="step2">
	<h4>Step 2: Choose image</h4>
	<table class="table">
		<tr>
			<td><label>Image:</label></td>
			<td>
				<div id="thumbs">

				</div>
				<input type="file" name="img_upload[]" accept="image/*" style="display: inline;" multiple="multiple">
			</td>
		</tr>
		<tr>
			<td><input type="button" value="Previous step 1" onClick="showStep1();"></td>
			<td><input type="button" value="Next step" onClick="showStep3();"></td>
		</tr>
	</table>
</div>
<div id="step3" class="step3">
	<style type="text/css">
		.text{width: 100%;}
		.text_field_name{font-weight: bold;}
		#field_remove{font-weight: bold; margin: 0 5px; padding: 0 3px; color: #aaa; cursor: pointer; border: 1px solid gray; background-color: #eee;}
		#field_remove:hover{color: red; background-color: #bbb;}
	</style>
	<h4>Step 3: Details of product</h4>
	<table class="table" id="table_step3">
		<tr>
			<td><label for="display">Display:</label></td>
			<td><input type="text" class="text" name="display" id="display"></td>
		</tr>
		<tr>
			<td><label for="os">OS:</label></td>
			<td><input type="text" class="text" name="os" id="os"></td>
		</tr>
		<tr>
			<td><label for="cpu">CPU:</label></td>
			<td><input type="text" class="text" name="cpu" id="cpu"></td>
		</tr>
		<tr>
			<td><label for="camera">Camera:</label></td>
			<td><input type="text" class="text" name="camera" id="camera"></td>
		</tr>
		<tr>
			<td><label for="internal_memory">Internal memory:</label></td>
			<td><input type="text" class="text" name="internal_memory" id="internal_memory"></td>
		</tr>
		<tr>
			<td><label for="ram">RAM:</label></td>
			<td><input type="text" class="text" name="ram" id="ram"></td>
		</tr>
		<tr>
			<td><label for="battery">Battery:</label></td>
			<td><input type="text" class="text" name="battery" id="battery"></td>
		</tr>
	</table>
	<table class="table">
		<tr>
			<td colspan="2">
				<input type="button" id="add_field" value="Add field">
			</td>
		</tr>
		<tr>
			<td><input type="button" value="Previous step 2" onClick="showStep2();"></td>
			<td><input type="button" value="Create"></td>
		</tr>
	</table>
</div>